[package]
name = "eguiquizst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.26.0"
serde = "1.0.196"
toml = "0.8.10"
serde_derive = "1.0.196"
