[questions]
racist = "how many i's are there in bingobopolopolis"
racistawnsers = "0 no u dont see any i's yo can fucking see"
racisttwo = "do you like coffee"
racistawnserstwo = "fucking loser"
racistthree = "gobbleygoop"
racistawnsersthree = "yeah idk i ran out"